### ISSUE TITLE
Filtro 5 meses para calculo da media 

### ISSUE THREAD

**Issue by julioriffel** [codenation-dev/squad-4-ad-python-2#25]
O consulta está retornando os últimos 5 registros.
O resultado pode se estender em múltiplos meses em  casos que não existe registro em um ou mais meses.

https://github.com/codenation-dev/squad-4-ad-python-2/blob/461008c711bad373c79bdb3c716f7f400c5b8292/api/views/check_comission.py#L65

**Comment by luanfsf** [comment]
Enviei um pergunta para o Elysson, para sobre como deveria ser a implementação, pois ficou muito aberto para interpretação.

**Comment by luanfsf** [comment]
Validado com o Elysson que podem ser consideradas as últimas 5 vendas.
